Don't apply formatOptions unless systemd-makefs is not being used
anduril/jetpack-nixos pull request #137
Opened 2023-10-03 20:56 UTC by jmbaur

###### Description of changes

With commit
https://github.com/nixos/nixpkgs/commit/5176a4f11356a338331d82e63563f8510b67317d, the option `fileSystems.<name>.options` will contain an "x-systemd.makefs". Since systemd-makefs does not take any parameters (but has sane defaults and actually uses fat32 for vfat fstype), the `formatOptions` option was made internal only and set to null. Let's set it null here unless systemd-makefs is not being used.

Fixes #105 

###### Testing

Tested that the assertion https://github.com/NixOS/nixpkgs/blob/28562b6c75906da822189e6f93bf45768dc04ee6/nixos/modules/tasks/filesystems.nix#L323 does not fail when evaluating a nixos config (using nixpkgs/nixos-unstable) with som xavier-agx and mountFirmwareEsp set to true. Also tested with nixpkgs/nixos-23.05 that formatOptions is a string with the value "-F 32 -n ESP".

2023-10-07 23:09 UTC, danielfullmer requested changes

2023-10-07 23:09 UTC, danielfullmer commented on modules/devices.nix
> +      formatOptions = if (lib.any (opt: opt == "x-systemd.makefs") config.options) then null else "-F 32 -n ESP";
Is this just to condition on NixOS version? The better way would be to condition on `config.system.nixos.release`

2023-10-07 23:10 UTC, danielfullmer commented
Does the UEFI capsule update test still pass on Xavier AGX?  The only thing we lose with this change is setting the filesystem label to "ESP", but I'm not sure whether the capsule update depends on that or not.

2023-10-09 15:15 UTC, jmbaur commented
I have not yet tested capsule updates with this change. From what I can see, systemd-makefs does not use a deterministic FS label.

2023-11-02 22:07 UTC, jmbaur commented
I verified that this change does not break capsule updates on Xavier devices. Since we reference the partition label and not the filesystem label, systemd-makefs would not influence any change in how we mount the partition.

2023-11-03 02:57 UTC, merged

2023-11-03 02:57 UTC, danielfullmer commented
Thanks!