Patch efitools to write to eMMC FAT partition
anduril/jetpack-nixos pull request #81
Opened 2023-05-11 21:16 UTC by jmbaur

###### Description of changes

For the xavier agx where efivars is mounted read-only and EFI variable
modifications must happen through an eMMC FAT partition, use a patched
efitools so that writes from the `efi-updatevar` utility are written to
the correct location.

###### Testing

Manually tested `efi-updatevar` with the patch applied on an xavier-agx devkit

2023-05-12 00:43 UTC, danielfullmer requested changes

2023-05-12 00:43 UTC, danielfullmer commented on modules/devices.nix
> +  systemd.tmpfiles.rules = [ "d /opt/nvidia/esp/EFI/NVDA/Variables 0755 root root -" ];
What is the effect of this if /opt/nvidia/esp is not mounted?

2023-05-12 00:43 UTC, danielfullmer commented on modules/devices.nix
> +  nixpkgs.overlays = [
Shouldn't this only be applied if `som == "xavier-agx"`

2023-05-12 00:43 UTC, danielfullmer commented on uefi-firmware.nix
> +      nativeBuildInputs = [ bc pythonEnv acpica-tools dtc util-linux ];
This is an unrelated change, so I'd recommend doing this in another PR

2023-05-14 00:17 UTC, closed without merging

2023-05-14 00:18 UTC, jmbaur commented
Closed since patching one tool that wants to write to the efivarfs kinda opens a can of worms for patching all tools that want to do this.